class Data:
    PHONE_NAME = 'Nokia C300'
    SENTENCE = 'Empower your day-to-day'
    FEATURE_1 = 'Up to 2-day battery life for uninterrupted usage'
    FEATURE_2 = 'Stunning photos with 13MP triple rear camera and 8MP front camera'
    FEATURE_3 = 'Powerful octa-core processor for seamless multitasking'
    PRICE = '$109.99\n$139.99'
    CHOOSE_COLOR = 'Go ahead and choose your color'
    BLUE = 'Blue'
    CHOOSE_CAPACITY = 'Now choose your capacity'
    STORAGE = '3 GB RAM, 32 GB Storage, Single SIM\n$109.99\n$139.99'
    CHOOSE_CARRIER = 'Use with any carrier'
    AVAILABLE_AT = 'This device is available both carrier-locked and unlocked.'
    BOTTOM_TEXT_1 = '*If ordered on a weekend, public holiday or after 13.00 on the last business day of the week, the order will be shipped on the following business day.'
    BOTTOM_TEXT_2 = '**15-day remorse period applies to phones and accessories. Remorse period for services may differ.'
    UNLOCKED_BUTTON_PARAGRAPH = 'This unlocked device works with any major US carrier or MVNO (both GSM and CDMA), including, but not limited to, T-Mobile, Verizon, AT&T, Tracfone, Metro, Boost, Consumer Cellular. Always double check compatibility, as compatibility may differ on a device-by-device basis. All devices sold on hmd.com are unlocked. Learn more about unlocked devices'
    AVAILABLE_AT2 = 'Available at'
    PRICING_NOTE = 'Pricing may vary between different retailers and depending on product specifications such as memory and storage.'
